### ISSUE TITLE
IAR Embedded Workbench IDE  (6.10.1.52143)  can't work

### ISSUE THREAD

**Issue by lanxb** [armink/CmBacktrace#10]
![image](https://user-images.githubusercontent.com/11402908/34597212-526d3b2c-f220-11e7-89c2-20f5fd1b0bab.png)
![image](https://user-images.githubusercontent.com/11402908/34597220-6136fec2-f220-11e7-944c-0c3ea1e7b801.png)

**Comment by lanxb** [comment]
fixed it!

![image](https://user-images.githubusercontent.com/11402908/34598696-3c8e0436-f229-11e7-8ecc-cb1b1732cdd2.png)

**Comment by armink** [comment]
Thx. You can give a pull request.

**Comment by armink** [comment]
fixed it on #13
