### ISSUE TITLE
堆栈溢出问题

### ISSUE THREAD

**Issue by ctwfei** [armink/CmBacktrace#11]
默认栈是向上生长？cm_backtrace_init初始化时判断一下栈的生长方向是否更好

**Comment by armink** [comment]
cortex-m 好像都是向下生长的吧

**Comment by ctwfei** [comment]
是我理解错了，看到stack start address时以为这就是栈顶
    /* **C stack block start address**, defined on linker script file, default is _sstack */
    #ifndef CMB_CSTACK_BLOCK_START
    #define CMB_CSTACK_BLOCK_START         _sstack
    #endif

    if (stack_pointer < stack_start_addr || stack_pointer > stack_start_addr + stack_size) {
        stack_is_overflow = true;
    }

**Comment by armink** [comment]
OK，那 issue 先 close 了。
