### ISSUE TITLE
M0, 除0操作时，并不进入HardFault 中断， 可能会是什么原因呢？（见 4 楼）

### ISSUE THREAD

**Issue by rh-chen** [armink/CmBacktrace#14]

**Comment by armink** [comment]
https://github.com/armink/CmBacktrace/blob/master/demos/non_os/stm32f10x/app/src/fault_test.c#L34

确定下这一位有没有置 1

**Comment by rh-chen** [comment]
代码上是有这句的：
``

**Comment by FatMeatball** [comment]
M0不是硬件除法器，是软件库处理的除法，所以不会进入进入HardFault 。

**Comment by armink** [comment]
原来如此，涨知识了~
