### ISSUE TITLE
makefile编译的时候必须要添加打印才能出现div 0 异常, 否则就直接输出0

### ISSUE THREAD

**Issue by wutianjun5858** [armink/CmBacktrace#19]
void fault_test_by_div0(void) {
    volatile int *SCB_CCR = (volatile int *)0xE000ED14;// SCB->CCR
    int x, y, z;
    My_printf("****"); // 添加这一句才能使用div 0 异常
    *SCB_CCR |= (1 << 4); /* bit4: DIV_0_TRP. */

    x = 10;
    y = 0;
    z = x / y;
    My_printf("z:%d\r\n", z);
}

**Comment by armink** [comment]
会不会是被 GCC 给优化掉了

**Comment by wutianjun5858** [comment]
还真的是这个情况,谢啦
